FROM docker.io/envoyproxy/envoy-distroless:v1.24.12@sha256:64947105ceb0b3eed9b9c8452a0bbe04c208ddc51d38b1a77135ab025e659d8c

# Just take the base image verbatim, as this doesn't have any fixable
# vulnerabilities at the time of writing.
