name: Build
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  prepare:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          matrix=$(./gen-matrix.sh)
          echo matrix="$matrix" >> $GITHUB_OUTPUT

  images:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        image_tag: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Determine image path
        id: imagepath
        run: echo "value=./images/${IMAGE_TAG//://}" >> $GITHUB_OUTPUT
        env:
          IMAGE_TAG: ${{ matrix.image_tag }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build agent
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ steps.imagepath.outputs.value }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: quay.io/k0sproject/${{ matrix.image_tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/k0sproject/${{ matrix.image_tag }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
