name: Build
on:
  push:
    branches:
      - main
jobs:
  prepare:
    name: Generate matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
      - id: set-matrix
        run: |
          matrix=$(./gen-matrix.sh)
          echo matrix="$matrix" >> $GITHUB_OUTPUT

  images:
    runs-on: ubuntu-22.04
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        image_tag: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Determine image path
        id: imagepath
        run: |
          echo "base=${IMAGE_TAG//://}" >> $GITHUB_OUTPUT
          echo "value=./images/${IMAGE_TAG//://}" >> $GITHUB_OUTPUT
        env:
          IMAGE_TAG: ${{ matrix.image_tag }}
      - name: Checkout
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - id: set-arch
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        run: |
          if [[ "${{ matrix.image_tag }}" =~ ^envoy.* ]]; then
            echo "archs=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
          else
            echo "archs=linux/amd64,linux/arm64,linux/arm/v7" >> $GITHUB_OUTPUT
          fi

      - name: Build agent
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ steps.imagepath.outputs.value }}
          platforms: ${{ steps.set-arch.outputs.archs }}
          push: true
          tags: quay.io/k0sproject/${{ matrix.image_tag }}

      - name: Run Trivy vulnerability
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: quay.io/k0sproject/${{ matrix.image_tag }}
          ignore-unfixed: true
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ contains(needs.prepare.outputs.changed_files, steps.imagepath.outputs.base) }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
