name: Build custom airgap image bundle
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - './hack/custom-airgap-*/**'

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Run git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build airgap image bundle
        run: |
          cd ./hack/custom-airgap-bundle-1.26.3
          ./create-bundle.sh

      - name: Upload bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: k0s-custom-airgap-1.26.3.tar
          path: ./hack/custom-airgap-bundle-1.26.3/k0s-custom-airgap-1.26.3.tar
